import json

truths = [
    "Apakah warna kegemaran anda?",
    "Pernah meniru dalam ujian?",
    "Adakah anda menyanyi dalam bilik mandi?",
    "Apakah snek kegemaran anda?",
    "Pernah berbohong kepada ibu bapa?",
    "Apakah kartun kegemaran anda?",
    "Adakah anda bercakap dengan haiwan peliharaan anda?",
    "Pernah kencing dalam kolam?",
    "Apakah tabiat pelik anda?",
    "Apakah filem kegemaran anda?",
    "Pernah menangis semasa menonton filem?",
    "Emoji yang paling kerap anda guna?",
    "Siapakah selebriti kegemaran anda?",
    "Adakah anda percaya pada hantu?",
    "Pernah suka pada guru anda?",
    "Apakah perkara terakhir yang anda cari di Google?",
    "Adakah anda tidur dengan patung mainan?",
    "Apakah mimpi paling pelik yang pernah anda alami?",
    "Pernah menari seorang diri dalam bilik?",
    "Adakah anda tahu tarian TikTok?",
    "Pernah kentut dan salahkan orang lain?",
    "Apakah perisa aiskrim kegemaran anda?",
    "Apakah ketakutan terbesar anda?",
    "Suka nanas atas piza?",
    "Pernah korek hidung di tempat awam?",
    "Siapa yang paling kerap anda hantar mesej?",
    "Adakah anda masih tidur dengan lampu terbuka?",
    "Apakah bakat rahsia anda?",
    "Makanan paling teruk yang pernah anda rasa?",
    "Pernah ketawa sampai menangis?",
    "Pernah ada kawan khayalan?",
    "Pernah lupa nama seseorang sejurus selepas berkenalan?",
    "Adakah anda suka nama anda?",
    "Perkataan yang selalu anda sebut salah?",
    "Perayaan kegemaran anda?",
    "Adakah anda percaya pada makhluk asing?",
    "Permainan kegemaran anda?",
    "Lagu yang anda rahsiakan suka?",
    "Siri TV yang menjadi 'guilty pleasure' anda?",
    "Apa perkara kecil yang paling menjengkelkan bagi anda?",
    "Subjek sekolah kegemaran?",
    "Siapakah adiwira kegemaran anda?",
    "Lagu terakhir yang anda dengar?",
    "Pernah bercakap semasa tidur?",
    "Minuman kegemaran anda?",
    "Pernah ponteng sekolah?",
    "Adakah anda percaya pada karma?",
    "Adakah anda menyanyi karaoke?",
    "Siapakah cinta monyet anda?",
    "Berapa lama anda pernah tak mandi?",
    "Apa rutin pagi anda?",
    "Pernah bawa makanan masuk ke kelas?",
    "Bau kegemaran anda?",
    "Adakah anda tidur dengan stokin?",
    "Pernah pecahkan sesuatu dan diamkan saja?",
    "Haiwan kegemaran anda?",
    "Pernah menangis tanpa sebab?",
    "Masa kegemaran dalam sehari?",
    "Pernah makan makanan yang jatuh ke lantai?",
    "Pernah lupa hari jadi seseorang?",
    "Anda tahu bersiul?",
    "Gabungan makanan paling pelik yang anda suka?",
    "Apa yang paling buat anda ketawa?",
    "Percaya pada cinta pandang pertama?",
    "Apa penipuan paling teruk anda pernah buat?",
    "Pernah pura-pura sakit?",
    "Lawak kegemaran anda?",
    "Sayur yang anda paling tak suka?",
    "Pernah simpan diari rahsia?",
    "Warna cadar katil anda?",
    "Apa yang anda memang tak pandai buat?",
    "Alasan kegemaran anda?",
    "Adakah anda berjalan semasa tidur?",
    "Suka hari hujan?",
    "Pernah berbohong dalam permainan?",
    "Adakah anda bercakap dengan diri sendiri?",
    "Suka filem seram?",
    "Pernah lupa nama orang semasa memperkenalkan mereka?",
    "Apa yang anda selalu bawa dalam beg?",
    "Adakah anda suka menyendiri?",
    "Kerja rumah yang anda paling tak suka?",
    "Apakah gambar terakhir dalam telefon anda?",
    "Topping piza kegemaran anda?",
    "Adakah anda ada nama panggilan?",
    "Pernah sesat?",
    "Suka kucing atau anjing?",
    "Apa kerja impian anda?",
    "Pernah kena tahan atau didenda di sekolah?",
    "Pencuci mulut kegemaran anda?",
    "Adakah anda percaya pada nasib?",
    "Berapa masa skrin anda hari ini?",
    "Apa pembohongan terakhir anda?",
    "Pernah makan terlalu banyak dan menyesal?",
    "Siapa yang paling anda kagumi?",
    "Pernah menangis sebab lagu sedih?",
    "Pakaian kegemaran anda?",
    "Apa yang orang selalu salah faham tentang anda?",
    "Bau kegemaran anda?",
    "Kenangan kegemaran anda?",
    "Anda suka matahari terbit atau terbenam?"
]

dares = [
    "Lakukan 10 lompatan bintang.",
    "Nyanyi lagu selama 10 saat.",
    "Buat muka paling kelakar anda.",
    "Bercakap dengan suara pelik selama 1 minit.",
    "Lakonkan haiwan kegemaran anda.",
    "Menari seperti ayam.",
    "Tiru selebriti kegemaran anda.",
    "Cuba jilat siku anda.",
    "Sebut abjad secara terbalik.",
    "Pusing 10 kali dan cuba berjalan lurus.",
    "Lakon ketawa jahat terbaik anda.",
    "Berlagak seperti kucing selama 30 saat.",
    "Sebut ayat susah 3 kali.",
    "Lukis misai di muka anda.",
    "Cuba sentuh jari kaki anda selama 10 saat.",
    "Bertindak seperti robot selama 1 minit.",
    "Pakai baju secara terbalik untuk pusingan ini.",
    "Buat topi pelik guna tisu.",
    "Berjalan seperti ketam selama 10 saat.",
    "Bercakap tanpa gerakkan bibir.",
    "Ambil selfie lucu dan tunjukkan.",
    "Berpura-pura dalam iklan syampu.",
    "Seimbangkan buku di atas kepala.",
    "Menyalak seperti anjing.",
    "Buat bunyi babi selama 15 saat.",
    "Berlagak seperti adiwira.",
    "Lakukan gaya catwalk.",
    "Bercakap dengan loghat British.",
    "Eja nama anda dengan badan anda.",
    "Tahan nafas selama 10 saat.",
    "Buat bentuk hati dengan tangan dan pose.",
    "Berlagak memberus gigi tanpa berus sebenar.",
    "Lompat atas satu kaki 15 kali.",
    "Berlagak menangis macam bayi.",
    "Bersenandung lagu kegemaran anda.",
    "Jelirkan lidah dan tahan selama 20 saat.",
    "Beri ucapan 10 saat tentang kenapa piza terbaik.",
    "Buat 3 bunyi haiwan berbeza.",
    "Lakonkan watak filem kegemaran anda.",
    "Lukis muka kelakar guna tangan bukan dominan.",
    "Cuba sentuh hidung dengan lidah anda.",
    "Makan benda masam tanpa buat reaksi.",
    "Berlagak seperti pelayan restoran.",
    "Cipta nama panggilan untuk diri sendiri.",
    "Pura-pura kasut anda adalah telefon.",
    "Berdiri macam patung selama 30 saat.",
    "Cuba juggling 2 objek.",
    "Buat pose balet terbaik anda.",
    "Tahan posisi plank selama 15 saat.",
    "Buat bunyi kelakar setiap kali orang kata 'ya' untuk pusingan ini.",
    "Balut diri anda dengan selimut seperti burrito.",
    "Bercakap seperti robot sampai giliran anda semula.",
    "Cuba buat handstand di dinding.",
    "Cuba moonwalk.",
    "Eja nama anda guna barang sekeliling.",
    "Buat 10 squat.",
    "Menari tanpa muzik.",
    "Berlagak seperti sedang berenang.",
    "Tiru lanun.",
    "Tiru seseorang dalam kumpulan.",
    "Kerdip mata tanpa henti selama 10 saat.",
    "Buat muka ikan.",
    "Tepuk tangan 20 kali dengan cepat.",
    "Buat aksi roda (atau pura-pura).",
    "Lukis sesuatu dengan mata tertutup.",
    "Seimbangkan objek di kepala selama 10 saat.",
    "Makan sehiris lemon.",
    "Bercakap dalam rima selama 1 minit.",
    "Buat menara guna barang berdekatan.",
    "Cuba ikat tali kasut dengan satu tangan.",
    "Berlagak telefon anda rosak dan panik.",
    "Berpura-pura jadi influencer terkenal.",
    "Buat bunyi seperti enjin kereta dihidupkan.",
    "Berlagak jadi DJ parti.",
    "Jerit satu perkataan rawak setiap 10 saat selama 1 minit.",
    "Peluk diri sendiri sambil kata 'Saya terbaik!'",
    "Ambil gambar olok-olok semua orang.",
    "Sebut sesuatu yang baik tentang setiap orang dalam kumpulan.",
    "Berlagak seperti model fesyen.",
    "Tepuk tangan guna kaki.",
    "Gunakan tangan sebagai boneka dan bercakap.",
    "Nyanyi korus lagu rawak.",
    "Berjalan macam penguin keliling bilik.",
    "Eja perkataan sambil menari.",
    "Buat mahkota guna benda sekeliling.",
    "Nyatakan ayat anda dengan nyanyian untuk pusingan ini.",
    "Main gitar udara selama 20 saat.",
    "Tari Macarena.",
    "Gaya rambut kelakar (atau pura-pura).",
    "Ceritakan lawak—baik atau buruk.",
    "Berlagak jadi hos rancangan memasak.",
    "Buat pusingan catwalk.",
    "Makan sesuatu sambil mata tertutup.",
    "Berpura-pura menang anugerah dan beri ucapan.",
    "Buat muka raksasa terbaik anda.",
    "Jadi pembaca berita dan laporkan sesuatu lucu.",
    "Berpura-pura bersin secara dramatik.",
    "Duduk atas lantai dan berpusing.",
    "Lakukan satu pose yoga.",
    "Sebut nama anda secara terbalik."
]



# Generate the formatted list
output = []

# Add truths
for i, truth in enumerate(truths, 1601):
    output.append({
        "id": str(i),
        "type": "TRUTH",
        "difficulty": "SIMPLE",
        "language": "MY",
        "content": truth
    })

# Add dares
for i, dare in enumerate(dares, len(truths) + 1601):
    output.append({
        "id": str(i),
        "type": "DARE",
        "difficulty": "SIMPLE",
        "language": "MY",
        "content": dare
    })

# Optional: Export to JSON file
with open("truth_or_dare_questions_simple_MY.json", "w") as f:
    json.dump(output, f, indent=2)
